### ISSUE TITLE
How to Stop getting Script error

### ISSUE THREAD

**Issue by vssaran** [KoenZomers/OneDriveAPI#15]
Hi All,
 OneDriveAPI  is working fine but i am getting a Script Error when i try to authorize my account. Can I know how to overcome this error.

Additional query, is it possible to download zip folder using OneDriveAPI .

**Comment by jonas-s-s-s** [comment]
Hello,
paste `webBrowser.ScriptErrorsSuppressed = true;` into your MainForm_Load() sub or
click on your webBrowser control and set the property "ScriptErrorsSuppressed" to true, like this:
![screenshot](https://user-images.githubusercontent.com/13944761/50490824-78dc4700-0a0f-11e9-9d4a-2786b7203181.png)

This sovled the issue for me, the script error is still happening but the annoying error window isn't displayed. It doesn't really matter if the script error is still happening, it occured because some image failed to load which doesnt effect the page usability.

**Comment by KoenZomers** [comment]
Thanks @jonasxxx for your clear suggestion. I've just updated the code of the demo application to surpress the JavaScript errors. The error thrown indeed does no harm and can safely be ignored.
